// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWbtw77v39fyCzrNfTw_Trdofrf0uh4qA',
    appId: '1:119620232467:web:988492dfcec4331347e6e6',
    messagingSenderId: '119620232467',
    projectId: 'godavari-agro',
    authDomain: 'godavari-agro.firebaseapp.com',
    storageBucket: 'godavari-agro.appspot.com',
    measurementId: 'G-W9KCH1WWQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-wIiXd4rIH-PJ3eYZM8Pg6mz8G0KdvaE',
    appId: '1:119620232467:android:e8feb94346f6664447e6e6',
    messagingSenderId: '119620232467',
    projectId: 'godavari-agro',
    storageBucket: 'godavari-agro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeJTP5ceCw_wAqkqSU7nzSw9A7nCFJmQg',
    appId: '1:119620232467:ios:a0c7013e5e41f59947e6e6',
    messagingSenderId: '119620232467',
    projectId: 'godavari-agro',
    storageBucket: 'godavari-agro.appspot.com',
    iosClientId:
        '119620232467-plbnsclcvpbp22943l9c4h3dthnfiqjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.maizeApp',
  );
}
